// ============================================================
// Notification listeners (Phase 2.7)
//
// Subscribe to domain events and create in-app / push notifications
// off the request hot path. Each handler is best-effort: failures
// are logged but never bubble up to the emitter.
//
// If pg-boss is ready we enqueue a background job; otherwise we
// invoke the helper inline so dev without DATABASE_URL still works.
// ============================================================

import { on } from "../lib/events.js";
import {
  createNotification,
  orderPaidNotification,
  offerReceivedNotification,
  offerAcceptedNotification,
  offerDeclinedNotification,
  listingApprovedNotification,
  listingRejectedNotification,
  newMessageNotification,
} from "../lib/notifications.js";
import {
  enqueue,
  isJobQueueReady,
  JOB_SEND_NOTIFICATION,
  type SendNotificationJobData,
} from "../lib/jobs.js";

async function dispatchNotification(data: SendNotificationJobData): Promise<void> {
  if (isJobQueueReady()) {
    await enqueue(JOB_SEND_NOTIFICATION, data);
    return;
  }
  await createNotification({
    user_id: data.user_id,
    type: data.type as never,
    title: data.title,
    body: data.body,
    data: data.data,
  });
}

export function registerNotificationListeners(): void {
  on("order:created", async (payload) => {
    const template = orderPaidNotification(
      payload.listingTitle,
      payload.amount,
      payload.currency,
      payload.sellerPayout
    );
    await dispatchNotification({
      user_id: payload.sellerId,
      type: "order_paid",
      ...template,
      data: { listing_id: payload.listingId, order_id: payload.orderId },
    });
  });

  on("offer:received", async (payload) => {
    const template = offerReceivedNotification(
      payload.buyerName,
      payload.listingTitle,
      payload.amount,
      payload.currency
    );
    await dispatchNotification({
      user_id: payload.sellerId,
      type: "offer_received",
      ...template,
      data: { listing_id: payload.listingId, offer_id: payload.offerId },
    });
  });

  on("offer:accepted", async (payload) => {
    const template = offerAcceptedNotification(
      payload.listingTitle,
      payload.amount,
      payload.currency
    );
    await dispatchNotification({
      user_id: payload.notifyUserId,
      type: "offer_accepted",
      ...template,
      data: { listing_id: payload.listingId, offer_id: payload.offerId },
    });
  });

  on("offer:rejected", async (payload) => {
    const template = offerDeclinedNotification(
      payload.listingTitle,
      payload.amount,
      payload.currency
    );
    await dispatchNotification({
      user_id: payload.notifyUserId,
      type: "offer_declined",
      ...template,
      data: { listing_id: payload.listingId, offer_id: payload.offerId },
    });
  });

  on("listing:approved", async (payload) => {
    const template = listingApprovedNotification(payload.title);
    await dispatchNotification({
      user_id: payload.sellerId,
      type: "listing_approved",
      ...template,
      data: { listing_id: payload.listingId },
    });
  });

  on("listing:rejected", async (payload) => {
    const template = listingRejectedNotification(payload.title, payload.reason);
    await dispatchNotification({
      user_id: payload.sellerId,
      type: "listing_rejected",
      ...template,
      data: { listing_id: payload.listingId },
    });
  });

  on("message:sent", async (payload) => {
    const template = newMessageNotification(payload.senderName);
    await dispatchNotification({
      user_id: payload.recipientId,
      type: "new_message",
      title: template.title,
      body: payload.preview || template.body,
      data: {
        conversation_id: payload.conversationId,
        listing_id: payload.listingId,
      },
    });
  });

  on("review:created", async (_payload) => {
    // Review notifications are generated by the reviews route once
    // both parties have posted. No listener action needed yet -- kept
    // for future expansion.
  });

  on("user:signed_up", async (_payload) => {
    // Welcome flow handled by email listener; nothing to push.
  });
}
